import {db,createRun,insertSnapshot,log,currentHash} from '@/lib/storage';
import {universe,companySnapshot} from '@/lib/providers';
import {sameOrigin,json,body} from '@/lib/http';
const publicRun=(r:any)=>({...r,universe:undefined,retry_queue:undefined,retryPending:JSON.parse(r.retry_queue||'[]').length});
export async function POST(req:Request){try{sameOrigin(req);const b=await body(req),d=db();if(b.action==='start'){
 const previous=await d.prepare("SELECT * FROM strategy_runs WHERE source='SEC/Yahoo' AND status IN ('running','partial') ORDER BY created_at DESC LIMIT 1").first();if(previous&&previous.strategy_hash===currentHash()&&(previous.offset<previous.total||JSON.parse(previous.retry_queue||'[]').length))return json({run:publicRun(previous)});
 const recent=await d.prepare("SELECT created_at FROM strategy_runs WHERE source='SEC/Yahoo' ORDER BY created_at DESC LIMIT 1").first();if(recent&&Date.now()-Date.parse(recent.created_at)<60000)return json({error:'انتظر دقيقة قبل إعادة محاولة الفحص.'},429);
 const id=await createRun('SEC/Yahoo');try{const companies=await universe();if(!companies.length)throw Error('SEC returned an empty universe');await d.prepare('UPDATE strategy_runs SET universe=?,total=?,stage=1 WHERE id=?').bind(JSON.stringify(companies),companies.length,id).run();await log(id,'universe',`Loaded ${companies.length} exchange-listed SEC symbols; security classification pending`);}catch(e:any){await d.prepare("UPDATE strategy_runs SET status='failed',error=? WHERE id=?").bind(e.message,id).run();return json({error:'تعذّر تحميل دليل الشركات: '+e.message},502)}return json({run:publicRun(await d.prepare('SELECT * FROM strategy_runs WHERE id=?').bind(id).first())});
 }
 if(b.action==='step'&&typeof b.runId==='string'){
 let r=await d.prepare('SELECT * FROM strategy_runs WHERE id=?').bind(b.runId).first();if(!r)return json({error:'الفحص غير موجود'},404);if(r.strategy_hash!==currentHash())return json({error:'تغيرت الاستراتيجية. ابدأ فحصًا جديدًا.'},409);if((r.offset>=r.total&&!JSON.parse(r.retry_queue||'[]').length)||!['running','partial'].includes(r.status))return json({run:publicRun(r)});
 const lock=await d.prepare("UPDATE strategy_runs SET lease_until=?,status='running' WHERE id=? AND lease_until<? AND offset=? AND retry_queue=?").bind(Date.now()+90000,r.id,Date.now(),r.offset,r.retry_queue).run();if(!lock.meta.changes)return json({error:'الفحص قيد التنفيذ في نافذة أخرى. أعد المحاولة بعد قليل.'},409);
 const companies=JSON.parse(r.universe||'[]');const retrying=r.offset>=r.total;const queue=JSON.parse(r.retry_queue||'[]');const entries=retrying?queue.slice(0,2):companies.slice(r.offset,r.offset+2).map((company:any)=>({company,attempt:0}));const remaining=retrying?queue.slice(2):queue;let success=0,failed=0,lastError='';const writes=[];
 for(const entry of entries){const c=entry.company;try{const s=await companySnapshot(c);writes.push(insertSnapshot(r.id,s));success++;}catch(e:any){failed++;lastError=e.message;if(entry.attempt<2)remaining.push({company:c,attempt:entry.attempt+1});await log(r.id,'company',`${c.ticker}: ${lastError}`);}}
 const offset=retrying?r.offset:r.offset+entries.length,totalFailed=retrying?r.failed-success:r.failed+failed,status=offset>=r.total?(totalFailed?'partial':'complete'):failed===entries.length?'partial':'running';
 writes.push(d.prepare('UPDATE strategy_runs SET offset=?,processed=processed+?,failed=?,stage=?,status=?,error=?,updated_at=?,lease_until=0,retry_queue=? WHERE id=?').bind(offset,success,totalFailed,offset>=r.total?13:4,status,lastError||r.error,new Date().toISOString(),JSON.stringify(remaining),r.id));await d.batch(writes);
 r=await d.prepare('SELECT * FROM strategy_runs WHERE id=?').bind(r.id).first();return json({run:publicRun(r)});
 }return json({error:'عملية غير صالحة'},400)}catch(e:any){return json({error:e.message||'تعذّر إكمال الفحص. النتائج السابقة محفوظة.'},503)}}
