import test from 'node:test';
import assert from 'node:assert/strict';
import {WEIGHTS,validateObservation,validateOpportunityDataset} from '../research/opportunity-validation.mjs';
const row=()=>({symbol:'FIXTURE',issuerId:'CIK-1',asOf:'2020-01-01',factors:Object.fromEntries(Object.keys(WEIGHTS).map(id=>[id,{score:5,sources:[{id:'SYNTHETIC',availableAt:'2019-12-01',periodEnd:'2019-09-30'}]}])),coverage:{membershipAsOf:'2020-01-01',delistedIncluded:true,corporateActionsComplete:true,outcomesComplete:true},prices:{adjustment:'split-adjusted-with-cash-dividends',entry:{at:'2020-01-02',price:10},bars:Array.from({length:183},(_,i)=>new Date(Date.parse('2020-01-02')+i*864e5)).filter(d=>d.getUTCDay()>0&&d.getUTCDay()<6).map(d=>({at:d.toISOString().slice(0,10),close:d.toISOString().slice(0,10)==='2020-04-01'?15:d<Date.parse('2020-04-01')?10:12,dividend:d.toISOString().slice(0,10)==='2020-04-01'?1:0})),observedUntil:'2020-07-02'},costs:{roundTripBps:100},benchmark:{source:'SYNTHETIC benchmark',totalReturn:.05}});
test('fixed-weight validation includes dividends, costs, executable entries and censored outcomes',()=>{const r=validateObservation(row(),Date.parse('2021-01-01'));assert.equal(r.valid,true);assert.equal(r.score,50);assert.equal(r.majorUpside,true);assert(Math.abs(r.totalReturn-.29)<1e-10);assert(Math.abs(r.maxDrawdown+3/16)<1e-10);assert.equal(validateObservation(row(),Date.parse('2020-06-01')).valid,false);const short=row();short.prices.bars.pop();short.prices.observedUntil='2020-04-01';assert.equal(validateObservation(short,Date.parse('2021-01-01')).censored,true);});
test('future evidence and unsupported membership/actions cannot validate opportunity claims',()=>{for(const change of [r=>r.factors.valuation.sources[0].availableAt='2020-02-01',r=>r.coverage.delistedIncluded=false,r=>r.prices.entry.at='2019-12-31',r=>delete r.costs]){const r=row();change(r);assert.equal(validateObservation(r,Date.parse('2021-01-01')).valid,false);}const report=validateOpportunityDataset([row(),row()],{cutoff:Date.parse('2021-01-01')});assert.equal(report.status,'BLOCKED');assert.equal(report.counts.rejected,1);assert.equal(report.probability,null);assert.equal(Object.values(report.weights).reduce((a,b)=>a+b,0),100);});
test('delisting proceeds include terminal loss rather than dropping the issuer',()=>{const r=row();r.prices.bars=r.prices.bars.filter(bar=>bar.at<'2020-03-01');r.prices.delisting={at:'2020-03-01',proceedsPerShare:0};r.prices.observedUntil='2020-03-01';const result=validateObservation(r,Date.parse('2021-01-01'));assert.equal(result.valid,true);assert.equal(result.censored,false);assert.equal(result.totalReturn,-1.01);assert.equal(result.maxDrawdown,-1);});

test('outcome coverage flags cannot substitute missing price sessions or permit impossible entry dates',()=>{
 const sparse=row();sparse.prices.bars=[sparse.prices.bars[0],sparse.prices.bars.at(-1)];assert.equal(validateObservation(sparse,Date.parse('2021-01-01')).censored,true);
 const late=row();late.prices.entry.at='2020-08-01';assert.equal(validateObservation(late,Date.parse('2021-01-01')).valid,false);
 const payoff=row();payoff.prices.delisting={at:'2019-12-31',proceedsPerShare:0};assert.equal(validateObservation(payoff,Date.parse('2021-01-01')).valid,false);
});
