'use client';
import {Star,RefreshCw,X} from 'lucide-react';
import {Sheet,SheetContent,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import type {Snapshot,Provenance,SecFilingResearch} from '@/lib/engine';
import type {OpportunityEvaluation} from '@/lib/opportunity-engine';
import {money,price,percent,day,mark} from './radar-format';
import PriceChart from './price-chart';

type Props={snapshot:Snapshot|null;opportunityEvaluation:OpportunityEvaluation|null;loading:boolean;error:string;favorite:boolean;onClose:()=>void;onRetry:()=>void;onFavorite:()=>void;onCopy:()=>void};
const safeLink=(url?:string)=>url&&/^https?:\/\//.test(url)?url:undefined;
const financialMetricLabels:Record<string,string>={revenue:'الإيرادات',grossProfit:'مجمل الربح المعلن',netIncome:'صافي الدخل',operatingIncome:'الدخل التشغيلي',operatingCashFlow:'التدفق النقدي التشغيلي',capitalExpenditure:'الإنفاق الرأسمالي',stockBasedCompensation:'تعويضات الأسهم',unrestrictedCash:'النقد غير المقيّد المعلن',totalDebt:'إجمالي الدين المعياري',freeCashFlowTtm:'التدفق النقدي الحر لآخر 4 أرباع',operatingIncomeTtm:'الدخل التشغيلي لآخر 4 أرباع',interestExpenseTtm:'مصروف الفائدة لآخر 4 أرباع',debtDueWithin24Months:'الأصل المستحق خلال 24 شهرًا'};
function Source({p}:{p?:Provenance}){return p?<small className="source-note">{safeLink(p.url)?<a href={p.url} target="_blank" rel="noreferrer">{p.source} ↗</a>:p.source} · {day(p.periodEnd)}{p.conversion&&<span className="source-conversion" dir="ltr"> · {p.conversion.sourceCurrency}→{p.conversion.targetCurrency} @ {p.conversion.rate.toPrecision(7)} · {p.conversion.ratePeriodStart}…{p.conversion.ratePeriodEnd} · {p.conversion.observationCount} rates · SEC available {p.conversion.inputAvailableAt} · {p.conversion.rateProvider} · <a href={safeLink(p.conversion.sourceUrl)} target="_blank" rel="noreferrer">FX rate source ↗</a></span>}</small>:<small className="source-note">المصدر التفصيلي غير متاح</small>}

export function SecFilingEvidence({research}:{research:SecFilingResearch}){
 const status=research.providerStatus==='retrieved'?'تم جلب الفهرس':research.providerStatus==='partial'?'الفهرس جزئي؛ استُبعدت سجلات غير صالحة':research.providerStatus==='empty'?'لا توجد ملفات ضمن الفهرس الحديث':research.providerStatus==='unavailable'?'تعذّر جلب الفهرس':'فشل التحقق من هوية بيانات الفهرس';
 const itemIndex=research.form8KItemIndex;
 return <details className="audit-details sec-filings"><summary>إفصاحات الشركة الأولية · {research.items.length} · {status}</summary><p>روابط إلى فهرس SEC لتسهيل المراجعة. بيانات الملف لا تثبت محتواه أو إلزاميته أو أثره الاستثماري، ولا تُعد محفزًا مستقبليًا بحد ذاتها. أحدث الفهرس محدود؛ راجع ملف SEC نفسه قبل أي استنتاج.</p>{itemIndex&&<section className="sec-filing-items"><h4>فهرس بنود 8-K · {itemIndex.fetchedDocuments}/{itemIndex.selectedDocuments} ملفات</h4><p>أرقام البنود التي ظهرت في نص الملفات الحديثة لتوجيه المراجعة فقط؛ لا تمثل تصنيفًا للمحفز أو تقييمًا للمحتوى.</p>{itemIndex.items.map(item=><p key={`8k-${item.accession}`}><a href={safeLink(item.url)} target="_blank" rel="noreferrer" dir="ltr">8-K · {item.filed} · {item.accession}</a><b dir="ltr">{item.referencedItemNumbers.length?`Items ${item.referencedItemNumbers.join(', ')}`:'No supported item number detected'}</b></p>)}{itemIndex.limitations.map((item,index)=><p className="muted" key={`8k-limit-${index}`}>{item}</p>)}</section>}{research.items.length>0&&<ul className="news-list">{research.items.map((item,index)=><li key={`${item.accession}-${index}`}><a href={safeLink(item.url)} target="_blank" rel="noreferrer"><p dir="ltr"><b>{item.form}</b> · {item.title}</p><div><span>SEC EDGAR · {item.filed}{item.reportDate?` · الفترة ${item.reportDate}`:''}</span><time dir="ltr">{item.accession}</time></div></a></li>)}</ul>}{research.limitations.map((item,index)=><p className="muted" key={`filing-limit-${index}`}>{item}</p>)}<Source p={research.source}/></details>;
}

type FinancialStrengthResearch=NonNullable<NonNullable<Snapshot['opportunityResearch']>['financialStrength']>;
type TechnicalTimingResearch=NonNullable<NonNullable<Snapshot['opportunityResearch']>['technicalTiming']>;
export function FinancialStrengthEvidence({research}:{research:FinancialStrengthResearch}){
 const count=Object.keys(research.metrics).length;
 return <details className="audit-details financial-history"><summary>أدلة القوة المالية والسيولة · {count}/6 مدخلات</summary><p>{research.readyForScoring?'اكتملت المدخلات المنظمة؛ يظل التقييم مشروطًا بملاءمة نموذج القطاع وصحة الفترات والعملة.':`التغطية الحالية: ${count}/6. النقص يمنع احتساب العامل ولا يُعامل كقيمة صفرية.`}</p><dl className="data-grid">{Object.entries(research.metrics).map(([key,metric])=><div key={key}><dt>{financialMetricLabels[key]||key}</dt><dd dir="ltr">{metric.unit==='USD'?`$${money(metric.value)}`:`${money(metric.value)} ${metric.unit}`}</dd><Source p={metric.source}/></div>)}</dl>{research.missing.map((item,index)=><p className="warning-note" key={`financial-gap-${index}`}>{item}</p>)}{research.conflicts.map((item,index)=><p className="warning-note" key={`financial-conflict-${index}`}>تعارض يحتاج مراجعة: {item}</p>)}{research.limitations.map((item,index)=><p className="muted" key={`financial-limit-${index}`}>{item}</p>)}</details>;
}
export function TechnicalTimingEvidence({research}:{research:TechnicalTimingResearch}){
 const bars=`${research.dailyBars} يومية · ${research.weeklyBars} أسبوعية · ${research.monthlyBars} شهرية · ${research.benchmarkBars} للمؤشر`;
 return <details className="audit-details financial-history"><summary>التوقيت الفني · {bars}</summary><p>{research.score.score==null?'لم يُحتسب وزن العامل البالغ 3%؛ لا تُحوّل البيانات الناقصة أو غير المصرّح بإعادة عرضها إلى درجة.':`الدرجة التشخيصية ${research.score.score.toFixed(1)} من 10؛ لا تمثل احتمال عائد.`}</p><p>{research.splitAdjusted?'تاريخ الأسعار المعدّل للتجزئة متاح.':'لم يتم التحقق من تعديل التجزئة.'} · حالة الحقوق: {research.rightsStatus}</p>{research.missing.map((item,index)=><p className="warning-note" key={`technical-gap-${index}`}>{item}</p>)}{research.score.score!=null&&<dl className="data-grid">{Object.entries(research.score.indicators).map(([key,value])=><div key={key}><dt>{key}</dt><dd dir="ltr">{key==='relativeStrength63d'?percent(value):value.toFixed(2)}</dd></div>)}</dl>}{research.assessment&&<Source p={research.assessment.source}/>}</details>;
}

export default function CompanySheet({snapshot:s,opportunityEvaluation,loading,error,favorite,onClose,onRetry,onFavorite,onCopy}:Props){
 const rangePosition=s?.price!=null&&s.low52w!=null&&s.high52w!=null&&s.high52w>s.low52w?Math.max(0,Math.min(100,(s.price-s.low52w)/(s.high52w-s.low52w)*100)):null;
 const upside=s?.targetMean!=null&&s.price!=null&&s.price>0?s.targetMean/s.price-1:null;
 return <Sheet open={!!s} onOpenChange={open=>{if(!open)onClose()}}><SheetContent side="bottom" className="company-sheet" showCloseButton={false} dir="rtl">
  <div className="sheet-grip"/><header className="sheet-toolbar"><SheetTitle>{s?.symbol||'ملف الشركة'}</SheetTitle><button className="copy-button" onClick={onCopy}>نسخ الرمز</button><button className={`star-button ${favorite?'saved':''}`} aria-label={favorite?'إزالة من المفضلة':'إضافة للمفضلة'} onClick={onFavorite}><Star fill={favorite?'currentColor':'none'} size={23}/></button><button className="sheet-top-close" aria-label="إغلاق ملف الشركة" onClick={onClose}><X size={20}/></button></header><SheetDescription className="sr-only">بيانات الشركة والأسعار والمعايير والمصادر المؤرخة</SheetDescription>
  {s&&opportunityEvaluation&&<div className="sheet-scroll" key={s.symbol}>
   <section className="company-summary opportunity"><div><h2 dir="ltr">{s.symbol}</h2><p dir="rtl" className="company-arabic-name">{s.nameAr||s.name}</p>{s.nameAr&&<small className="company-original-name" dir="ltr">{s.name}</small>}<div className="detail-price"><b dir="ltr">{price(s.price)}</b><span className={s.dailyChange==null?'muted':s.dailyChange>=0?'pass':'fail'}>{s.dailyChange==null?'تغير الجلسة غير متاح':`${percent(s.dailyChange)} آخر جلسة`}</span></div><p dir="rtl">{s.industryAr||s.industry||s.sectorAr||s.sector||s.exchange||'السوق غير متاح'} · ${money(s.marketCap)}</p><Source p={s.provenance.price}/></div><div className="detail-score"><strong>{opportunityEvaluation.score>0?opportunityEvaluation.score.toFixed(1):'—'}</strong><span>{opportunityEvaluation.state==='ranked'?'من 100 · مكتمل':'نقاط مثبتة · مقام 100'}</span><small>تغطية الأوزان: {opportunityEvaluation.coveragePct.toFixed(1)}%</small></div></section>
   {loading&&<p className="inline-loading" role="status"><RefreshCw size={16} className="spin"/> جارٍ جلب التاريخ وملف الشركة والأخبار…</p>}
   {error&&<div className="message error" role="alert"><span>{error} — احتُفظ باللقطة السابقة.</span><button onClick={onRetry}>إعادة المحاولة</button></div>}
   <section className="detail-strategy opportunity"><h3>{opportunityEvaluation.state==='ranked'?'مؤهلة للترتيب':opportunityEvaluation.state==='excluded'?'مستبعدة بدليل':'تحتاج بحثًا'} · الفرص الاستثمارية الموحدة</h3><p>{opportunityEvaluation.reason} النقاط الخوارزمية مؤقتة عند نقص التغطية، وليست توصية استثمارية.</p></section><section className="model-disclosure"><b>نموذج الفرص الموحد · {opportunityEvaluation.horizonMonths} أشهر</b><span>نسخة {opportunityEvaluation.version} · الثقة {opportunityEvaluation.confidence==='high'?'عالية':opportunityEvaluation.confidence==='medium'?'متوسطة':'منخفضة'} · لا يوجد اعتماد تنبؤي.</span></section><div className="opportunity-detail-factors" aria-label="عوامل تقييم الفرصة">{opportunityEvaluation.factors.map(f=><article key={f.id} className={f.complete?'complete':f.evidenced?'partial':''}><div><b>{f.label}</b><span>الوزن {f.weight}%</span></div><strong>{f.score!=null?`${f.score.toFixed(1)} / 10`:'غير مثبت'}</strong><small>{f.proxy&&!f.evidenced?`درجة خوارزمية مؤقتة · نقاط العامل ${f.points.toFixed(2)} · التغطية المؤهلة ${f.coveragePct.toFixed(0)}%`:f.evidenced?`نقاط العامل ${f.points.toFixed(2)} · تغطية وزنه ${f.coveragePct.toFixed(0)}%`:f.rationale}</small>{(f.evidenced||f.proxy)&&<small>{f.rationale}</small>}<small>المصادر: {f.sources.length} · {f.evidenced?f.sources.map(p=>p.source).join('، '):f.proxy?'الدرجة مشتقة آليًا؛ لا تمثل مراجعة مصدرية كاملة':'لا يوجد دليل مؤهل'}</small></article>)}</div><section className="criteria"><h3>بوابات السلامة والدليل</h3><ul>{opportunityEvaluation.checks.map(check=><li key={check.id}><b><span className={check.status.toLowerCase()}>{mark[check.status]}</span> {check.id}</b><span>{check.explanation}</span></li>)}</ul></section>
   <PriceChart key={s.symbol} snapshot={s} loading={loading}/>
   <section className="detail-box"><h3>ماذا تفعل الشركة</h3><p dir={s.descriptionAr?'rtl':'auto'}>{s.descriptionAr||s.description||'الوصف غير متاح من مصدر موثق.'}</p><small>{s.description&&!s.descriptionAr?'الترجمة العربية غير متاحة مؤقتًا؛ النص الأصلي محفوظ أدناه.':''}</small><p className="muted" dir="rtl">{[s.sectorAr||s.sector,s.industryAr||s.industry,s.employees!=null?`${s.employees.toLocaleString('en-US')} موظف`:null].filter(Boolean).join(' · ')||'القطاع والصناعة غير متاحين'}</p><Source p={s.provenance.description}/></section>
   <section className="financial-section"><h3>البيانات المالية</h3><dl className="data-grid">{([
    ['revenue','الإيرادات',s.revenue],['revenueGrowth','نمو الإيرادات',s.revenueGrowth],['grossMargin','الهامش الإجمالي',s.grossMargin],['netIncome','صافي الدخل',s.netIncome],['fcf','التدفق النقدي الحر',s.fcf],['cash','النقد',s.cash],['debt','الدين',s.debt],['medianDollarVolume20d','السيولة اليومية',s.medianDollarVolume20d],['evSales','قيمة المنشأة / المبيعات',s.evSales],['ps','السعر / المبيعات',s.ps],['dilution','تخفيف الأسهم',s.dilution],
   ] as const).map(([key,label,value])=><div key={key}><dt>{label}</dt><dd dir="ltr">{value==null?'غير متاح':['dilution','revenueGrowth','grossMargin'].includes(key)?percent(value):['evSales','ps'].includes(key)?value.toFixed(2):`$${money(value)}`}</dd><Source p={s.provenance[key]}/></div>)}</dl></section>
   {s.opportunityResearch?.financialStrength&&<FinancialStrengthEvidence research={s.opportunityResearch.financialStrength}/>}
   {s.opportunityResearch?.technicalTiming&&<TechnicalTimingEvidence research={s.opportunityResearch.technicalTiming}/>}
   <div className="earnings-pair"><section className="detail-box"><h3>التقرير القادم</h3><strong dir="ltr">{day(s.nextEarnings)}</strong><Source p={s.provenance.nextEarnings}/></section><section className={`detail-box ${s.lastEarningsStatus==='إيجابي'?'positive-box':s.lastEarningsStatus==='سلبي'?'negative-box':''}`}><h3>آخر تقرير</h3><strong>{s.lastEarningsStatus||'غير معروف'}</strong><p>{day(s.lastEarnings)}</p><Source p={s.provenance.lastEarnings}/></section></div>
   <section className="detail-box analyst-box"><div className="section-line"><h3>متوسط أهداف المحللين</h3>{upside!=null&&<b className={upside>=0?'pass':'fail'} dir="ltr">{percent(upside)}</b>}</div><div className="target-value"><strong dir="ltr">{s.targetMean==null?'غير متاح':price(s.targetMean)}</strong><span>النطاق {s.targetLow!=null&&s.targetHigh!=null?`${s.targetLow}–${s.targetHigh}`:'غير متاح'} · {s.analystCount??'عدد غير متاح'} محلل</span></div><p className="muted">هذه آراء المحللين وليست «القيمة العادلة». لا تُستنتج أهداف عند غياب المصدر.</p>{s.targetMean==null&&s.analystTarget!=null&&<p>هدف سنة واحدة من Nasdaq: {price(s.analystTarget)} — ليس متوسطًا مثبتًا.</p>}<Source p={s.provenance.targetMean||s.provenance.analystTarget}/></section>
   <section className="year-range"><div className="section-line"><h3>الموقع في نطاق 52 أسبوعًا</h3><span>{rangePosition==null?'غير متاح':`${rangePosition.toFixed(0)}%`}</span></div>{rangePosition!=null?<div className="range-track" dir="ltr"><i style={{left:`${rangePosition}%`}}/></div>:<p className="muted">لا تتوفر بيانات كافية لحساب الموقع.</p>}<div className="range-labels"><span>أعلى {money(s.high52w)}</span><span>أدنى {money(s.low52w)}</span></div></section>
   <section><h3>مفاجآت الأرباح (الفعلي مقابل المتوقع)</h3>{s.surprises?.length?<div className="surprise-grid">{s.surprises.slice(-4).map((r,i)=><div key={`${r.quarter}-${i}`}><b className={r.surprisePct==null?'muted':r.surprisePct>=0?'pass':'fail'} dir="ltr">{r.surprisePct==null?'غير متاح':`${r.surprisePct>=0?'+':''}${r.surprisePct.toFixed(0)}%`}</b><small>{r.quarter}</small></div>)}</div>:<p className="muted">مفاجآت الأرباح غير متاحة.</p>}<Source p={s.provenance.surprises}/></section>
   <section className="detail-box"><h3>رصيد الطلبات (الإيراد المتعاقد عليه)</h3><p>{s.backlog?.amount!=null?`$${money(s.backlog.amount)} · ${day(s.backlog.asOf)}`:'لا يتوفر رقم موثق في البيانات المنظمة. قد يتطلب التحقق قراءة نص الإفصاح.'}</p>{s.backlog?.source&&safeLink(s.backlog.source)&&<a href={s.backlog.source} target="_blank" rel="noreferrer">الإفصاح ↗</a>}</section>
   <section><h3>أحدث الأخبار</h3>{s.news?.length?<ul className="news-list">{s.news.map((n,i)=><li key={`${n.title}-${i}`}><a href={safeLink(n.link)} target="_blank" rel="noreferrer"><p dir="rtl">{n.titleAr||n.title}</p>{n.titleAr&&<small className="news-original" dir="ltr">{n.title}</small>}<div><span>{n.sourceAr||n.source||'مصدر غير متاح'}</span><time>{day(n.publishedAt)}</time></div></a></li>)}</ul>:<p className="muted">لا تتوفر أخبار موثقة في هذه اللقطة.</p>}</section>
   {s.opportunityResearch?.secFilings&&<SecFilingEvidence research={s.opportunityResearch.secFilings}/>}
   <section className="detail-box"><h3>شراء المطلعين — Form 4، الرمز P فقط</h3>{s.insiderResearch&&<p className={s.insiderResearch.state==='complete'?'pass':'warning-note'}>{s.insiderResearch.state==='complete'?'تغطية كاملة للإفصاحات المتاحة في نافذة 12 شهرًا.':s.insiderResearch.state==='unavailable'?'تعذّر التحقق من تغطية إفصاحات المطلعين.':'تغطية جزئية؛ لا يُعامل غياب عملية شراء ظاهرة كدليل على عدم وجودها.'} {s.insiderResearch.message} · جُلب {s.insiderResearch.fetchedForm4Count}/{s.insiderResearch.selectedForm4Count}؛ تمت مراجعة {s.insiderResearch.reviewedForm4Count??0}، ملفات غير صالحة {s.insiderResearch.invalidForm4Count??0}، غير مجلوبة {s.insiderResearch.unattemptedForm4Count??0}، فشل الجلب {s.insiderResearch.failedForm4Count} · {s.insiderResearch.windowStart} — {s.insiderResearch.windowEnd}</p>}{s.insiderPurchases?.length?s.insiderPurchases.map((p,i)=><div className="insider-row" key={`${p.date}-${i}`}><span>{p.owner}<small>{p.date} · {p.shares.toLocaleString('en-US')} سهم</small></span><a href={safeLink(p.source)} target="_blank" rel="noreferrer">${money(p.value)} ↗</a></div>):<p className="muted">لا توجد مشتريات برمز P ضمن الإفصاحات المفحوصة. يلزم مستوى تغطية كامل قبل اعتبار ذلك نتيجة سلبية.</p>}</section>
   {s.opportunityResearch?.earnings&&<details className="audit-details financial-history"><summary>القوائم المالية المنظمة · 3 سنوات و8 أرباع</summary><p>{s.opportunityResearch.earnings.providerStatus==='unavailable'?'تعذّر جلب SEC Company Facts لهذه اللقطة؛ القيم غير المتاحة تحتاج إعادة المحاولة.':s.opportunityResearch.earnings.providerStatus==='empty'?'استجاب SEC لكن لا توجد حقائق US-GAAP/IFRS معيارية قابلة للاستخدام لهذا الملف.':s.opportunityResearch.earnings.providerStatus==='invalid'?'استجابة SEC لا تجتاز التحقق من هوية الشركة أو بنية البيانات؛ لن تُستخدم في التقييم.':s.opportunityResearch.earnings.providerStatus==='retrieved'?'تم التحقق من هوية استجابة SEC ووجود حقائق معيارية؛ التغطية ما تزال مرتبطة بالفترات والحقول الظاهرة أدناه.':'حالة استجابة SEC غير معروفة؛ لن تُعرض على أنها بيانات جرى التحقق منها.'} {s.opportunityResearch.earnings.providerMessage&&<span dir="ltr">({s.opportunityResearch.earnings.providerMessage})</span>}</p><p>السنة والفترة والقيم من SEC XBRL. حالة احتساب مؤشر جودة الأرباح: {s.opportunityResearch.earnings.readyForScoring?'المدخلات مكتملة حسابياً':'المدخلات غير مكتملة'}؛ هذا لا يعني اكتمال التحليل الاستثماري أو اعتماد توصية.</p>{s.opportunityResearch.earnings.missing.map((item,index)=><p className="warning-note" key={`${item}-${index}`}>{item}</p>)}{s.opportunityResearch.earnings.conflicts.map((item,index)=><p className="warning-note" key={`${item}-${index}`}>تعارض يحتاج مراجعة: {item}</p>)}{(['annual','quarterly'] as const).map(kind=><section key={kind}><h4>{kind==='annual'?'السنوات المالية':'الأرباع المستقلة'} · {kind==='annual'?s.opportunityResearch!.earnings.annual.length:s.opportunityResearch!.earnings.quarterly.length}</h4><div className="financial-periods">{s.opportunityResearch!.earnings[kind].map(period=><article className="detail-box financial-period" key={`${kind}-${period.start}-${period.end}`}><b dir="ltr">{period.start} — {period.end}</b><dl className="data-grid">{Object.entries(financialMetricLabels).map(([key,label])=>{const metric=period.metrics[key as keyof typeof period.metrics];return <div key={key}><dt>{label}</dt><dd dir="ltr">{metric?metric.unit==='USD'?`$${money(metric.value)}`:`${money(metric.value)} ${metric.unit}`:'غير متاح'}</dd>{metric&&<Source p={metric.source}/>}</div>})}</dl></article>)}</div></section>)}{s.opportunityResearch.earnings.limitations.map((item,index)=><p className="muted" key={`${item}-${index}`}>{item}</p>)}</details>}
   <section><h3>الإيرادات الربعية</h3>{s.revenueTrend?.length?<div className="revenue-bars">{s.revenueTrend.slice(-6).map((r,i)=>{const max=Math.max(...s.revenueTrend!.slice(-6).map(p=>p.value),1);return <div key={`${r.quarter}-${i}`}><span>${money(r.value)}</span><div className="bar-space"><i style={{height:`${Math.max(2,r.value/max*100)}%`}}/></div><small>{r.quarter}</small></div>})}</div>:<p className="muted">الإيرادات الربعية غير متاحة من مصدر موثق.</p>}</section>
   <details className="audit-details"><summary>مصادر كل قيمة والتحذيرات</summary>{s.dataIssues?.map((issue,i)=><p key={i} className="warning-note">{issue}</p>)}<dl>{Object.entries(s.provenance).map(([key,p])=><div key={key}><dt>{key}</dt><dd><Source p={p}/><small>توفر: {p.availableAt} · جلب: {p.retrievedAt}</small></dd></div>)}</dl><p>وقت اللقطة: {s.asOf}</p></details>
  </div>}
  <footer className="sheet-footer"><button onClick={onClose}>إغلاق ×</button></footer>
 </SheetContent></Sheet>;
}
