'use client';
import {useMemo} from 'react';
import {Star,RefreshCw,X} from 'lucide-react';
import {Sheet,SheetContent,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {evaluateStrategy,SPECS,type Snapshot,type Provenance} from '@/lib/engine';
import {money,price,percent,day,checkLabel,mark,statusText} from './radar-format';
import PriceChart from './price-chart';

type Evaluation=ReturnType<typeof evaluateStrategy>;
type Props={snapshot:Snapshot|null;strategy:'core'|'bounce';baselineEvaluation:Evaluation|null;loading:boolean;error:string;favorite:boolean;onClose:()=>void;onRetry:()=>void;onFavorite:()=>void;onCopy:()=>void};
const safeLink=(url?:string)=>url&&/^https?:\/\//.test(url)?url:undefined;
function Source({p}:{p?:Provenance}){return p?<small className="source-note">{safeLink(p.url)?<a href={p.url} target="_blank" rel="noreferrer">{p.source} ↗</a>:p.source} · {day(p.periodEnd)}</small>:<small className="source-note">المصدر التفصيلي غير متاح</small>}

export default function CompanySheet({snapshot:s,strategy,baselineEvaluation,loading,error,favorite,onClose,onRetry,onFavorite,onCopy}:Props){
 const evaluation=useMemo(()=>s?evaluateStrategy(strategy,s):null,[s,strategy]);
 const displayed=baselineEvaluation??evaluation;
 const changed=!!baselineEvaluation&&!!evaluation&&(baselineEvaluation.score!==evaluation.score||baselineEvaluation.status!==evaluation.status||baselineEvaluation.checks.some((check,i)=>check.status!==evaluation.checks[i]?.status));
 const accepted=displayed?.screeningQualified;
 const plan=SPECS.bounce.exit;
 const rangePosition=s?.price!=null&&s.low52w!=null&&s.high52w!=null&&s.high52w>s.low52w?Math.max(0,Math.min(100,(s.price-s.low52w)/(s.high52w-s.low52w)*100)):null;
 const upside=s?.targetMean!=null&&s.price!=null&&s.price>0?s.targetMean/s.price-1:null;
 return <Sheet open={!!s} onOpenChange={open=>{if(!open)onClose()}}><SheetContent side="bottom" className="company-sheet" showCloseButton={false} dir="rtl">
  <div className="sheet-grip"/><header className="sheet-toolbar"><SheetTitle>{s?.symbol||'ملف الشركة'}</SheetTitle><button className="copy-button" onClick={onCopy}>نسخ الرمز</button><button className={`star-button ${favorite?'saved':''}`} aria-label={favorite?'إزالة من المفضلة':'إضافة للمفضلة'} onClick={onFavorite}><Star fill={favorite?'currentColor':'none'} size={23}/></button><button className="sheet-top-close" aria-label="إغلاق ملف الشركة" onClick={onClose}><X size={20}/></button></header><SheetDescription className="sr-only">بيانات الشركة والأسعار والمعايير والمصادر المؤرخة</SheetDescription>
  {s&&evaluation&&<div className="sheet-scroll" key={s.symbol}>
   <section className={`company-summary ${strategy}`}><div><h2 dir="ltr">{s.symbol}</h2><p dir="auto">{s.name}</p><div className="detail-price"><b dir="ltr">{price(s.price)}</b><span className={s.dailyChange==null?'muted':s.dailyChange>=0?'pass':'fail'}>{s.dailyChange==null?'تغير الجلسة غير متاح':`${percent(s.dailyChange)} آخر جلسة`}</span></div><p dir="auto">{s.industry||s.exchange||'السوق غير متاح'} · ${money(s.marketCap)}</p><Source p={s.provenance.price}/></div><div className="detail-score"><strong>{displayed?.score==null?'—':displayed.score.toFixed(1)}</strong><span>من 100 · ترتيب تشخيصي</span><small>تغطية الدرجة: {displayed?.scoreCoverage??0}% · ثقة {displayed?.ratingConfidence==='high'?'عالية':displayed?.ratingConfidence==='medium'?'متوسطة':'منخفضة'}</small></div></section>
   {changed&&<div className="message" role="status"><span>حُفظت درجة وقت الفحص كما ظهرت في البطاقة. التحقق العميق الحالي أعطى {evaluation?.score==null?'درجة غير متاحة':`${evaluation.score.toFixed(1)} من 100`} وحالة {evaluation?.status==='PASS'?'مستوفٍ':evaluation?.status==='FAIL'?'غير مستوفٍ':'غير مثبت'} بسبب بيانات أحدث أو أوسع.</span></div>}
   {loading&&<p className="inline-loading" role="status"><RefreshCw size={16} className="spin"/> جارٍ جلب التاريخ وملف الشركة والأخبار…</p>}
   {error&&<div className="message error" role="alert"><span>{error} — احتُفظ باللقطة السابقة.</span><button onClick={onRetry}>إعادة المحاولة</button></div>}
   <section className={`detail-strategy ${strategy}`}><h3>{accepted?'بوابات السلامة مؤكدة':displayed?.status==='FAIL'?'فشل بوابة سلامة':'بوابات السلامة تحتاج تحققًا'} · {strategy==='bounce'?'فرص الارتداد':'القيمة الأساسية'}</h3><p>{strategy==='bounce'?`الخطة المرجعية: هدف +${plan.target*100}%، وقف ${plan.stop*100}%، وخروج بعد ${plan.months} أشهر. الهبوط والانعكاس والتخفيف عوامل موزونة؛ فشل العامل يخفض الدرجة ولا يحذف السهم. الدرجة ليست احتمال ربح.`:'التقييم والربحية والنمو والميزانية عوامل موزونة. بوابات السلامة فقط تستطيع منع التصنيف، والدرجة الحالية تشخيصية حتى نجاح الاختبار التاريخي.'}</p><div className="check-chips">{displayed?.checks.filter(c=>c.role==='eligibility').map(c=><span key={c.id} className={c.status.toLowerCase()}>{checkLabel[c.id]||c.label}: {statusText[c.status]}</span>)}</div></section>
   <section className="model-disclosure"><b>حالة النموذج: غير معتمد تنبؤيًا</b><span>نسخة {displayed?.model?.version||SPECS[strategy].model.version} · احتمال النتيجة غير معروض لأن المعايرة التاريخية لم تجتز بوابة الاعتماد.</span></section>
   <div className="factor-grid" aria-label="تفصيل الدرجة الحالية">{displayed?.factors.map(f=><div key={f.id} title={`${f.explanation} · القيمة: ${f.rawValue??'غير متاحة'}`}><b>{f.available?f.points.toFixed(1):'—'}</b><span>{f.label}</span><small>من {f.maxPoints}</small></div>)}</div>
   <PriceChart key={s.symbol} snapshot={s} loading={loading}/>
   <section className="criteria"><h3>بوابات السلامة</h3><ul>{displayed?.checks.filter(c=>c.role==='eligibility').map(c=><li key={c.id}><b><span className={c.status.toLowerCase()}>{mark[c.status]}</span> {checkLabel[c.id]||c.label}</b><span>{c.explanation}</span></li>)}</ul></section>
   <section className="criteria"><h3>عوامل الترتيب الموزونة</h3><p className="muted">فشل عامل يخفض الدرجة ولا يحذف السهم من الترتيب.</p><ul>{displayed?.checks.filter(c=>c.role==='factor').map(c=><li key={c.id}><b><span className={c.status.toLowerCase()}>{mark[c.status]}</span> {checkLabel[c.id]||c.label}</b><span>{c.explanation}</span></li>)}</ul></section>
   <section className="criteria"><h3>جودة الدليل</h3><ul>{displayed?.checks.filter(c=>c.role==='evidence').map(c=><li key={c.id}><b><span className={c.status.toLowerCase()}>{mark[c.status]}</span> {checkLabel[c.id]||c.label}</b><span>{c.explanation}</span></li>)}</ul></section>
   <section className="detail-box"><h3>ماذا تفعل الشركة</h3><p dir={s.descriptionAr?'rtl':'auto'}>{s.descriptionAr||s.description||'الوصف غير متاح من مصدر موثق.'}</p><small>{s.description&&!s.descriptionAr?'النص الأصلي من المصدر؛ الترجمة العربية غير متاحة.':''}</small><p className="muted" dir="auto">{[s.sector,s.industry,s.employees!=null?`${s.employees.toLocaleString('en-US')} موظف`:null].filter(Boolean).join(' · ')||'القطاع والصناعة غير متاحين'}</p><Source p={s.provenance.description}/></section>
   <section className="financial-section"><h3>البيانات المالية</h3><dl className="data-grid">{([
    ['revenue','الإيرادات',s.revenue],['netIncome','صافي الدخل',s.netIncome],['fcf','التدفق النقدي الحر',s.fcf],['cash','النقد',s.cash],['debt','الدين',s.debt],['medianDollarVolume20d','السيولة اليومية',s.medianDollarVolume20d],['evSales','قيمة المنشأة / المبيعات',s.evSales],['ps','السعر / المبيعات',s.ps],['dilution','تخفيف الأسهم',s.dilution],
   ] as const).map(([key,label,value])=><div key={key}><dt>{label}</dt><dd dir="ltr">{value==null?'غير متاح':key==='dilution'?percent(value):['evSales','ps'].includes(key)?value.toFixed(2):`$${money(value)}`}</dd><Source p={s.provenance[key]}/></div>)}</dl></section>
   <div className="earnings-pair"><section className="detail-box"><h3>التقرير القادم</h3><strong dir="ltr">{day(s.nextEarnings)}</strong><Source p={s.provenance.nextEarnings}/></section><section className={`detail-box ${s.lastEarningsStatus==='إيجابي'?'positive-box':s.lastEarningsStatus==='سلبي'?'negative-box':''}`}><h3>آخر تقرير</h3><strong>{s.lastEarningsStatus||'غير معروف'}</strong><p>{day(s.lastEarnings)}</p><Source p={s.provenance.lastEarnings}/></section></div>
   <section className="detail-box analyst-box"><div className="section-line"><h3>متوسط أهداف المحللين</h3>{upside!=null&&<b className={upside>=0?'pass':'fail'} dir="ltr">{percent(upside)}</b>}</div><div className="target-value"><strong dir="ltr">{s.targetMean==null?'غير متاح':price(s.targetMean)}</strong><span>النطاق {s.targetLow!=null&&s.targetHigh!=null?`${s.targetLow}–${s.targetHigh}`:'غير متاح'} · {s.analystCount??'عدد غير متاح'} محلل</span></div><p className="muted">هذه آراء المحللين وليست «القيمة العادلة». لا تُستنتج أهداف عند غياب المصدر.</p>{s.targetMean==null&&s.analystTarget!=null&&<p>هدف سنة واحدة من Nasdaq: {price(s.analystTarget)} — ليس متوسطًا مثبتًا.</p>}<Source p={s.provenance.targetMean||s.provenance.analystTarget}/></section>
   <section className="year-range"><div className="section-line"><h3>الموقع في نطاق 52 أسبوعًا</h3><span>{rangePosition==null?'غير متاح':`${rangePosition.toFixed(0)}%`}</span></div>{rangePosition!=null?<div className="range-track" dir="ltr"><i style={{left:`${rangePosition}%`}}/></div>:<p className="muted">لا تتوفر بيانات كافية لحساب الموقع.</p>}<div className="range-labels"><span>أعلى {money(s.high52w)}</span><span>أدنى {money(s.low52w)}</span></div></section>
   <section><h3>مفاجآت الأرباح (الفعلي مقابل المتوقع)</h3>{s.surprises?.length?<div className="surprise-grid">{s.surprises.slice(-4).map((r,i)=><div key={`${r.quarter}-${i}`}><b className={r.surprisePct==null?'muted':r.surprisePct>=0?'pass':'fail'} dir="ltr">{r.surprisePct==null?'غير متاح':`${r.surprisePct>=0?'+':''}${r.surprisePct.toFixed(0)}%`}</b><small>{r.quarter}</small></div>)}</div>:<p className="muted">مفاجآت الأرباح غير متاحة.</p>}<Source p={s.provenance.surprises}/></section>
   <section className="detail-box"><h3>رصيد الطلبات (الإيراد المتعاقد عليه)</h3><p>{s.backlog?.amount!=null?`$${money(s.backlog.amount)} · ${day(s.backlog.asOf)}`:'لا يتوفر رقم موثق في البيانات المنظمة. قد يتطلب التحقق قراءة نص الإفصاح.'}</p>{s.backlog?.source&&safeLink(s.backlog.source)&&<a href={s.backlog.source} target="_blank" rel="noreferrer">الإفصاح ↗</a>}</section>
   <section><h3>أحدث الأخبار</h3>{s.news?.length?<ul className="news-list">{s.news.map((n,i)=><li key={`${n.title}-${i}`}><a href={safeLink(n.link)} target="_blank" rel="noreferrer"><p dir="auto">{n.title}</p><div><span>{n.source||'مصدر غير متاح'}</span><time>{day(n.publishedAt)}</time></div></a></li>)}</ul>:<p className="muted">لا تتوفر أخبار موثقة في هذه اللقطة.</p>}</section>
   <section className="detail-box"><h3>شراء المطّلعين — Form 4 P فقط</h3>{s.insiderPurchases?.length?s.insiderPurchases.map((p,i)=><div className="insider-row" key={`${p.date}-${i}`}><span>{p.owner}<small>{p.date} · {p.shares.toLocaleString('en-US')} سهم</small></span><a href={safeLink(p.source)} target="_blank" rel="noreferrer">${money(p.value)} ↗</a></div>):<p className="muted">لا تتوفر مشتريات موثقة. غياب البيانات ليس إثباتًا لعدم وجود شراء.</p>}</section>
   <section><h3>الإيرادات الربعية</h3>{s.revenueTrend?.length?<div className="revenue-bars">{s.revenueTrend.slice(-6).map((r,i)=>{const max=Math.max(...s.revenueTrend!.slice(-6).map(p=>p.value),1);return <div key={`${r.quarter}-${i}`}><span>${money(r.value)}</span><div className="bar-space"><i style={{height:`${Math.max(2,r.value/max*100)}%`}}/></div><small>{r.quarter}</small></div>})}</div>:<p className="muted">الإيرادات الربعية غير متاحة من مصدر موثق.</p>}</section>
   <details className="audit-details"><summary>مصادر كل قيمة والتحذيرات</summary>{s.dataIssues?.map((issue,i)=><p key={i} className="warning-note">{issue}</p>)}<dl>{Object.entries(s.provenance).map(([key,p])=><div key={key}><dt>{key}</dt><dd><Source p={p}/><small>توفر: {p.availableAt} · جلب: {p.retrievedAt}</small></dd></div>)}</dl><p>وقت اللقطة: {s.asOf}</p></details>
  </div>}
  <footer className="sheet-footer"><button onClick={onClose}>إغلاق ×</button></footer>
 </SheetContent></Sheet>;
}
