import type {Snapshot,Provenance} from './engine';
import {SPECS} from './engine';
import {ma30Weeks} from './research';
import {observations,latestInstant,trailingAnnual,provenance,REVENUE_TAGS} from './sec';
const userAgent='SmallCapRadar/2.0 (research; github.com/yousef-hamda)';
export async function fetchJson(url:string){let last:unknown;for(let attempt=0;attempt<2;attempt++){try{const r=await fetch(url,{headers:{'User-Agent':userAgent,Accept:'application/json'},signal:AbortSignal.timeout(18000)});if(!r.ok){if((r.status===429||r.status>=500)&&attempt===0){await new Promise(resolve=>setTimeout(resolve,300));continue}throw Error(`${new URL(url).hostname}: HTTP ${r.status}`)}return r.json()}catch(error){last=error;if(attempt===0){await new Promise(resolve=>setTimeout(resolve,300));continue}}}throw last instanceof Error?last:Error(`${new URL(url).hostname}: request failed`)}
export async function universe(){try{const j:any=await fetchJson('https://www.sec.gov/files/company_tickers_exchange.json');const fields=j.fields;return j.data.map((r:any[])=>Object.fromEntries(fields.map((f:string,i:number)=>[f,r[i]]))).filter((r:any)=>['Nasdaq','NYSE','NYSE American'].includes(r.exchange)&&/^[A-Z0-9.-]{1,12}$/.test(r.ticker))}catch(primary){try{const j:any=await fetchJson('https://www.sec.gov/files/company_tickers.json');return Object.values(j).map((r:any)=>({cik:r.cik_str,ticker:r.ticker,name:r.title,exchange:'unknown'})).filter((r:any)=>/^[A-Z0-9.-]{1,12}$/.test(r.ticker))}catch{throw primary}}}
export async function companySnapshot(company:any):Promise<Snapshot>{
 const now=new Date().toISOString(),symbol=company.ticker,cik=String(company.cik).padStart(10,'0'),url=`https://query1.finance.yahoo.com/v8/finance/chart/${encodeURIComponent(symbol)}?range=5y&interval=1d&events=splits`;
 const j:any=await fetchJson(url),result=j.chart?.result?.[0];if(!result)throw Error(`${symbol}: quote unavailable`);const meta=result.meta,q=result.indicators?.quote?.[0],timestamps=result.timestamp||[];
 const history=timestamps.map((t:number,i:number)=>({date:new Date(t*1000).toISOString().slice(0,10),close:q?.close?.[i],open:q?.open?.[i],high:q?.high?.[i],low:q?.low?.[i],volume:q?.volume?.[i]})).filter((r:any)=>r.close>0&&r.low>0);
 const quoteTime=new Date(meta.regularMarketTime*1000).toISOString();const quoteEvidence:Provenance={source:'Yahoo chart (experimental)',url,periodEnd:quoteTime.slice(0,10),availableAt:quoteTime,retrievedAt:now,currency:meta.currency,confidence:'medium'};
 const exchange=company.exchange==='unknown'?(meta.exchangeName||meta.fullExchangeName||'unknown'):company.exchange;
 const s:Snapshot={symbol,name:company.name,asOf:now,exchange,securityType:meta.instrumentType==='EQUITY'&&!/preferred|warrant|depositary.*share|fund|trust|\betf\b/i.test(company.name)?'common':'unknown',price:meta.currency==='USD'?meta.regularMarketPrice:null,confidence:'F',deathSpiral:'unknown',provenance:{price:quoteEvidence},history};
 if(meta.currency!=='USD')return s;
 const dv=history.slice(-20).map((r:any)=>r.close*r.volume).filter(Number.isFinite).sort((a:number,b:number)=>a-b);if(dv.length===20){s.medianDollarVolume20d=(dv[9]+dv[10])/2;s.provenance.medianDollarVolume20d=quoteEvidence;}
 const yearStart=Date.parse(quoteTime)-365*864e5,year=history.filter((r:any)=>Date.parse(r.date)>=yearStart),prior=history.filter((r:any)=>Date.parse(r.date)<=yearStart).at(-1);
 if(prior&&Date.parse(prior.date)>=yearStart-7*864e5&&s.price){s.return12m=s.price/prior.close-1;s.provenance.return12m=quoteEvidence;}
 if(year.length>=240){s.low52w=Math.min(...year.map((r:any)=>r.low));s.provenance.low52w=quoteEvidence;}
 s.ma30w=ma30Weeks(history,now);if(s.ma30w)s.provenance.ma30w=quoteEvidence;
 const factsUrl=`https://data.sec.gov/api/xbrl/companyfacts/CIK${cik}.json`;let facts:any;try{facts=await fetchJson(factsUrl)}catch(e:any){s.dataIssues=[`تعذّر جلب بيانات SEC: ${e.message}`];s.research={financials:false,valuation:false,analysts:false,sector:false};return s}const f=facts.facts;
 const shares=latestInstant(observations(f,['EntityCommonStockSharesOutstanding','CommonStockSharesOutstanding'],'shares'),now);
 // A filing share count is historical; mark cap estimate and do not silently treat as current verified market cap.
 if(shares&&s.price&&Date.parse(now)-Date.parse(shares.end)<120*864e5&&!Object.values(result.events?.splits||{}).some((split:any)=>split.date*1000>Date.parse(shares.end))){s.marketCap=shares.val*s.price;s.provenance.marketCap={...provenance(shares,factsUrl,now),source:'Derived: SEC reported shares × Yahoo price',availableAt:[provenance(shares,factsUrl,now).availableAt,quoteEvidence.availableAt].sort().at(-1)!,confidence:'low'};}
 if(s.marketCap!=null&&(s.marketCap<SPECS.core.marketCap.min||s.marketCap>SPECS.core.marketCap.max))return s;
 const shareRows=observations(f,['EntityCommonStockSharesOutstanding','CommonStockSharesOutstanding'],'shares').filter(r=>!r.start&&Date.parse(r.filed+'T23:59:59Z')<=Date.parse(now)&&Number.isFinite(r.val)).sort((a,b)=>b.end.localeCompare(a.end)||b.filed.localeCompare(a.filed));
 const currentShares=shareRows[0],priorShares=currentShares&&shareRows.find(r=>{const days=(Date.parse(currentShares.end)-Date.parse(r.end))/864e5;return days>=330&&days<=430});
 if(currentShares&&priorShares){const start=Date.parse(priorShares.end),end=Date.parse(currentShares.end);const splits=Object.values(result.events?.splits||{}).filter((event:any)=>event.date*1000>start&&event.date*1000<=end);const factor=splits.reduce((product:number,event:any)=>{const ratio=Number(event.numerator)/Number(event.denominator);return Number.isFinite(ratio)&&ratio>0?product*ratio:product},1);s.dilution=currentShares.val/(priorShares.val*factor)-1;s.splitAdjusted=true;s.provenance.dilution={source:'Derived: SEC shares, adjusted by Yahoo split events',url:factsUrl,periodStart:priorShares.end,periodEnd:currentShares.end,availableAt:[currentShares.filed+'T23:59:59Z',quoteEvidence.availableAt].sort().at(-1)!,retrievedAt:now,currency:'shares',tag:'EntityCommonStockSharesOutstanding',confidence:'medium'};}
 for(const [key,tags] of Object.entries({revenue:REVENUE_TAGS,netIncome:['NetIncomeLoss','ProfitLoss'],ocf:['NetCashProvidedByUsedInOperatingActivities'],capex:['PaymentsToAcquirePropertyPlantAndEquipment']})){
 const annual=trailingAnnual(observations(f,tags),now);if(annual){(s as any)[key]=annual.val;s.provenance[key]=provenance(annual,factsUrl,now);if(['20-F','40-F'].includes(annual.form))s.foreignFiler=true;}
 }
 const ocf=(s as any).ocf,capex=(s as any).capex;if(ocf!=null&&capex!=null&&s.provenance.ocf.periodEnd===s.provenance.capex.periodEnd){s.fcf=ocf-capex;s.provenance.fcf={...s.provenance.ocf,tag:'OperatingCashFlow − PaymentsToAcquirePropertyPlantAndEquipment',availableAt:[s.provenance.ocf.availableAt,s.provenance.capex.availableAt].sort().at(-1)!};}
 // EV and split-corrected dilution stay missing until a reliable debt/current-share feed is configured.
 if(s.marketCap&&s.revenue&&s.revenue>0){s.ps=s.marketCap/s.revenue;s.provenance.ps={...s.provenance.revenue,source:'Derived: estimated market cap / SEC revenue',availableAt:[s.provenance.marketCap.availableAt,s.provenance.revenue.availableAt].sort().at(-1)!,confidence:'low'}}
 s.confidence='C';s.research={financials:!!s.revenue,valuation:false,analysts:false,sector:false};delete (s as any).ocf;delete (s as any).capex;return s;
}
