import {SPECS} from './engine';
export type Bar={date:string;open:number;high:number;low:number;close:number};
export function expiryDate(entry:string,months=SPECS.bounce.exit.months){const d=new Date(entry+'T00:00:00Z');const day=d.getUTCDate();d.setUTCDate(1);d.setUTCMonth(d.getUTCMonth()+months);const last=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+1,0)).getUTCDate();d.setUTCDate(Math.min(day,last));return d.toISOString().slice(0,10)}
export function simulateExit(entry:number,entryDate:string,bars:Bar[],cost={slippageBps:0,commission:0,shares:1}){
 if(!(entry>0)||!Number.isFinite(entry)||cost.slippageBps<0||cost.slippageBps>=10000||cost.commission<0||!(cost.shares>0))throw Error('Invalid entry or costs');
 const stop=entry*(1+SPECS.bounce.exit.stop),target=entry*(1+SPECS.bounce.exit.target),expiry=expiryDate(entryDate);
 let fill:number|null=null,reason='open',date:string|null=null;
 for(const b of [...bars].sort((a,b)=>a.date.localeCompare(b.date))){if(b.date<entryDate)continue;if(![b.open,b.high,b.low,b.close].every(n=>Number.isFinite(n)&&n>0)||b.low>Math.min(b.open,b.close)||b.high<Math.max(b.open,b.close))throw Error('Invalid OHLC bar');
 // At expiry liquidate at the next observed tradable opening; no invented holiday bars.
 if(b.date>=expiry){fill=b.open;reason='time';date=b.date;break;}
 if(b.low<=stop){fill=Math.min(b.open,stop);reason='stop';date=b.date;break;}
 if(b.high>=target){fill=target;reason='target';date=b.date;break;}
 }
 const slip=cost.slippageBps/1e4,paid=entry*(1+slip)*cost.shares+cost.commission,received=fill==null?null:fill*(1-slip)*cost.shares-cost.commission;
 return {reason,date,fill,expiry,netReturn:received==null?null:received/paid-1,target,stop,convention:'stop-first same-bar; gap-down at open; target capped; expiry at first tradable open'};
}
export function pointInTime<T extends {availableAt?:string;periodEnd:string}>(rows:T[],at:string){const cutoff=Date.parse(at);if(!Number.isFinite(cutoff))throw Error('Invalid cutoff');return rows.filter(r=>{const t=r.availableAt?Date.parse(r.availableAt):Date.parse(r.periodEnd)+60*864e5;return Number.isFinite(t)&&t<=cutoff}).map(r=>({...r,availabilityEstimated:!r.availableAt}));}
export function firmHoldout(firmId:string,salt:string){if(!salt)throw Error('Permanent salt required');let n=2166136261;for(const c of `${salt}:${firmId}`){n^=c.charCodeAt(0);n=Math.imul(n,16777619)}const bucket=(n>>>0)%100;return bucket<60?'train':bucket<80?'validation':bucket<90?'locked':'final';}
export function bonferroni(p:number,experiments:number){if(p<0||p>1||!Number.isInteger(experiments)||experiments<1)throw Error('Invalid experiment');return Math.min(1,p*experiments)}
export function firmBootstrap(rows:{firm:string;value:number}[],iterations=1000,seed=42){if(!rows.length||iterations<1)throw Error('No observations');const firms=[...new Set(rows.map(r=>r.firm))].sort(),groups=firms.map(f=>rows.filter(r=>r.firm===f).map(r=>r.value));const rand=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296};const estimates=[];for(let i=0;i<iterations;i++){const sample=[];for(let j=0;j<firms.length;j++)sample.push(...groups[Math.floor(rand()*firms.length)]);estimates.push(sample.reduce((a,b)=>a+b,0)/sample.length)}estimates.sort((a,b)=>a-b);return {unit:'firm',firms:firms.length,low:estimates[Math.floor(iterations*.025)],high:estimates[Math.min(iterations-1,Math.floor(iterations*.975))]};}
export function splitAdjustedDilution(current:number,previous:number,splitFactor:number){return current>0&&previous>0&&splitFactor>0?current/(previous*splitFactor)-1:null;}
export function ma30Weeks(rows:{date:string;close:number}[],asOf:string){const cutoff=new Date(asOf);const day=cutoff.getUTCDay();const monday=new Date(cutoff);monday.setUTCDate(cutoff.getUTCDate()-((day+6)%7));monday.setUTCHours(0,0,0,0);const weeks=new Map<string,{date:string;close:number}>();for(const r of rows){const d=new Date(r.date+'T00:00:00Z');if(d>=monday||!(r.close>0))continue;d.setUTCDate(d.getUTCDate()-((d.getUTCDay()+6)%7));const key=d.toISOString().slice(0,10);if(!weeks.has(key)||weeks.get(key)!.date<r.date)weeks.set(key,r)}const last=[...weeks.entries()].sort((a,b)=>a[0].localeCompare(b[0])).slice(-30);if(last.length<30)return null;for(let i=1;i<last.length;i++)if(Date.parse(last[i][0])-Date.parse(last[i-1][0])!==7*864e5)return null;return last.reduce((n,[,r])=>n+r.close,0)/30;}
