import {z} from 'zod';
const number=z.number().finite().nullable().optional();
const timestamp=z.string().datetime({offset:true});
const evidence=z.object({source:z.string().min(1).max(200),url:z.string().url().refine(u=>u.startsWith('https://'),'HTTPS only').optional(),periodStart:z.string().optional(),periodEnd:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),availableAt:timestamp,retrievedAt:timestamp,currency:z.string().max(8).optional(),tag:z.string().max(200).optional(),confidence:z.enum(['high','medium','low'])});
export const snapshotSchema=z.object({symbol:z.string().regex(/^[A-Z0-9.^-]{1,16}$/),name:z.string().min(1).max(200),asOf:timestamp,cik:z.number().int().nonnegative().optional(),securityType:z.string().max(30).optional(),exchange:z.string().max(40).optional(),foreignFiler:z.boolean().optional(),price:number,marketCap:number,medianDollarVolume20d:number,revenue:number,evSales:number,ps:number,netIncome:number,fcf:number,return12m:number,low52w:number,ma30w:number,dilution:number,splitAdjusted:z.boolean().optional(),deathSpiral:z.enum(['clean','mild','elevated','severe','unknown']).optional(),riskEvidence:z.string().max(4000).optional(),liquidityReviewed:z.boolean().optional(),confidence:z.enum(['A','B','C','D','F']).optional(),research:z.object({financials:z.boolean().optional(),valuation:z.boolean().optional(),analysts:z.boolean().optional(),sector:z.boolean().optional()}).optional(),sourceConflicts:z.array(z.string().max(1000)).max(100).optional(),dataIssues:z.array(z.string().max(1000)).max(100).optional(),provenance:z.record(evidence),history:z.array(z.object({date:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),close:z.number().positive(),open:number,high:number,low:number,volume:number})).max(1500).optional()});
export const completeSnapshotSchema=snapshotSchema.extend({
 shareCountRatio:number,dailyChange:number,cash:number,debt:number,fcfYield:number,revenueGrowth:number,operatingMarginTrend:number,grossMargin:number,high52w:number,volume:number,averageVolume10d:number,
 analystTarget:number,targetMean:number,targetLow:number,targetHigh:number,analystCount:number,employees:number,insiderBuyValue:number,
 description:z.string().max(20000).optional(),descriptionAr:z.string().max(20000).optional(),website:z.string().url().max(500).optional(),sector:z.string().max(200).optional(),industry:z.string().max(200).optional(),
 nextEarnings:z.string().max(40).nullable().optional(),lastEarnings:z.string().max(40).nullable().optional(),lastEarningsStatus:z.enum(['إيجابي','سلبي','مختلط','غير معروف']).optional(),
 surprises:z.array(z.object({quarter:z.string().max(40),surprisePct:number,actual:number,estimate:number})).max(30).optional(),
 revenueTrend:z.array(z.object({quarter:z.string().max(40),value:z.number().finite(),periodEnd:z.string().optional()})).max(50).optional(),
 news:z.array(z.object({title:z.string().max(2000),link:z.string().url().refine(u=>/^https?:\/\//.test(u)).optional(),publishedAt:z.string().max(80).optional(),source:z.string().max(200).optional()})).max(100).optional(),
 insiderPurchases:z.array(z.object({owner:z.string().max(300),date:z.string().max(40),shares:z.number().finite().positive(),price:z.number().finite().nonnegative(),value:z.number().finite().nonnegative(),source:z.string().url().optional()})).max(100).optional(),
 backlog:z.object({amount:number,currency:z.string().max(8).optional(),asOf:z.string().max(40).optional(),stale:z.boolean().optional(),source:z.string().url().optional()}).nullable().optional(),
}).strict();
export const importSchema=z.array(completeSnapshotSchema).min(1).max(500).refine(rows=>new Set(rows.map(r=>r.symbol)).size===rows.length,'Duplicate symbols are not allowed');
