import {z} from 'zod';
const number=z.number().finite().nullable().optional();
const timestamp=z.string().datetime({offset:true});
const positiveCount=z.number().int().nonnegative().max(1000000);
const notes=z.array(z.string().max(4000)).max(150);
const sourceFields={
 source:z.string().min(1).max(300),url:z.string().url().refine(u=>u.startsWith('https:'),'HTTPS only').optional(),
 periodStart:z.string().optional(),periodEnd:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),availableAt:timestamp,retrievedAt:timestamp,
 currency:z.string().max(8).optional(),tag:z.string().max(1000).optional(),confidence:z.enum(['high','medium','low']),
 rightsStatus:z.enum(['public-domain','redistribution-permitted','licensed','personal-use-only','restricted','unknown']).optional(),
 scope:z.string().max(200).optional(),metricScope:z.string().max(300).optional(),accession:z.string().max(80).optional(),parserVersion:z.string().max(80).optional(),contentHash:z.string().regex(/^[a-f0-9]{64}$/).optional(),
 conversion:z.object({rate:z.number().finite().positive(),sourceCurrency:z.string().max(8),targetCurrency:z.literal('USD'),method:z.enum(['period-average-daily-reference-cross-rate','period-end-prior-daily-reference-cross-rate']),ratePeriodStart:z.string(),ratePeriodEnd:z.string(),observationCount:positiveCount,sourceUrl:z.string().url(),rateProvider:z.string().max(300),inputAvailableAt:timestamp,inputRetrievedAt:timestamp}).optional(),
};
function evidenceSchema(depth:number):z.ZodTypeAny{return z.object({...sourceFields,dependencies:depth?z.array(evidenceSchema(depth-1)).max(100).optional():z.array(z.never()).max(0).optional()});}
const evidence=evidenceSchema(6);
const metric=z.object({value:z.number().finite(),unit:z.string().max(16),source:evidence});
const earningsPeriod=z.object({start:z.string(),end:z.string(),metrics:z.object(Object.fromEntries(['revenue','grossProfit','netIncome','operatingIncome','operatingCashFlow','capitalExpenditure','stockBasedCompensation'].map(key=>[key,metric.optional()])))});
const currencyTranslation=z.object({state:z.enum(['complete','partial','unavailable']),sourceCurrency:z.string().max(8),targetCurrency:z.literal('USD'),annualConvertedPeriods:positiveCount,quarterlyConvertedPeriods:positiveCount,annualWithheldPeriods:positiveCount,quarterlyWithheldPeriods:positiveCount,source:z.string().max(300),disclosure:z.string().max(3000)});
const earningsResearch=z.object({currencyTranslation:currencyTranslation.optional(),providerStatus:z.enum(['retrieved','unavailable','empty','invalid']),providerMessage:z.string().max(2000).optional(),coverage:z.object({annualPeriodsFound:positiveCount,quarterlyPeriodsFound:positiveCount,selectedUnit:z.string().max(16)}),annual:z.array(earningsPeriod).max(20),quarterly:z.array(earningsPeriod).max(80),missing:notes,conflicts:notes,limitations:notes,readyForScoring:z.boolean()});
const financialResearch=z.object({providerStatus:z.enum(['retrieved','unavailable','empty','invalid']),industryModel:z.literal('industrial-operating-company').optional(),metrics:z.object(Object.fromEntries(['unrestrictedCash','totalDebt','freeCashFlowTtm','operatingIncomeTtm','interestExpenseTtm','debtDueWithin24Months'].map(key=>[key,metric.optional()]))),missing:notes,conflicts:notes,limitations:notes,readyForScoring:z.boolean()});
const filingObservation=z.object({id:z.string().max(100),kind:z.enum(['commercial','financing','governance','scheduled-event']),text:z.string().max(1000),eventDate:z.string().optional(),reviewStatus:z.literal('unreviewed'),scoreCredit:z.literal(0)});
const filingResearch=z.object({providerStatus:z.enum(['retrieved','partial','unavailable','empty','invalid']),indexEarliestFiled:z.string().optional(),items:z.array(z.object({form:z.string().max(40),filed:z.string(),reportDate:z.string().optional(),accession:z.string().max(40),title:z.string().max(400),url:z.string().url()})).max(100),source:evidence,limitations:notes,form8KItemIndex:z.object({providerStatus:z.enum(['retrieved','partial','unavailable','empty']),selectedDocuments:positiveCount,fetchedDocuments:positiveCount,failedDocuments:positiveCount,truncatedDocuments:positiveCount,items:z.array(z.object({accession:z.string().max(40),filed:z.string(),form:z.literal('8-K'),url:z.string().url(),referencedItemNumbers:z.array(z.string().max(8)).max(40),contentHash:z.string().regex(/^[a-f0-9]{64}$/).optional(),parserVersion:z.string().max(80).optional(),observations:z.array(filingObservation).max(40).optional()})).max(10),limitations:notes}).optional()});
const technicalScore=z.object({score:z.number().finite().min(0).max(10).nullable(),rationale:z.string().max(20000),sources:z.array(evidence).max(20),confidence:z.enum(['low','medium','high']).optional(),coveragePct:z.number().finite().min(0).max(100).optional(),conflicts:notes.optional(),calculation:z.object({rubricId:z.string().max(200),inputs:z.array(z.object({name:z.string().max(400),value:z.union([z.string().max(4000),z.number().finite()]),unit:z.string().max(40).optional()})).max(500)}).optional(),indicators:z.object(Object.fromEntries(['ma20','ma50','ma100','ma200','ma30w','rsi14','relativeStrength63d'].map(key=>[key,z.number().finite()])))});
const technicalResearch=z.object({asOf:timestamp,providerStatus:z.enum(['retrieved','unavailable','invalid']),dailyBars:positiveCount,weeklyBars:positiveCount,monthlyBars:positiveCount,benchmarkBars:positiveCount,splitAdjusted:z.boolean(),rightsStatus:z.enum(['public-domain','redistribution-permitted','licensed','personal-use-only','restricted','unknown']),score:technicalScore,missing:notes});
export const snapshotSchema=z.object({symbol:z.string().regex(/^[A-Z0-9.^-]{1,16}$/),name:z.string().min(1).max(200),asOf:timestamp,cik:z.number().int().nonnegative().optional(),securityType:z.string().max(30).optional(),listingStatus:z.enum(['current','not-confirmed-current']).optional(),exchange:z.string().max(40).optional(),foreignFiler:z.boolean().optional(),price:number,marketCap:number,medianDollarVolume20d:number,revenue:number,evSales:number,ps:number,netIncome:number,fcf:number,return12m:number,low52w:number,ma30w:number,dilution:number,splitAdjusted:z.boolean().optional(),deathSpiral:z.enum(['clean','mild','elevated','severe','unknown']).optional(),riskEvidence:z.string().max(4000).optional(),liquidityReviewed:z.boolean().optional(),confidence:z.enum(['A','B','C','D','F']).optional(),research:z.object({financials:z.boolean().optional(),valuation:z.boolean().optional(),analysts:z.boolean().optional(),sector:z.boolean().optional()}).optional(),sourceConflicts:z.array(z.string().max(1000)).max(100).optional(),dataIssues:z.array(z.string().max(1000)).max(100).optional(),provenance:z.record(evidence),history:z.array(z.object({date:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),close:z.number().positive(),open:number,high:number,low:number,volume:number})).max(1500).optional()});
export const completeSnapshotSchema=snapshotSchema.extend({
 peerContext:z.object({version:z.literal('sec-sic-size-period-v1'),asOf:timestamp,method:z.string().max(1000),grade:z.number().finite().min(0).max(10).nullable(),peers:z.array(z.object({symbol:z.string().max(16),cik:positiveCount,sic:positiveCount,end:z.string(),revenue:z.number().finite().positive(),grossMargin:z.number().finite(),sources:z.array(evidence).max(3)})).max(20),gaps:notes}).optional(),
 issuerCommonListingCount:positiveCount.optional(),adrRatio:z.object({value:z.number().finite().positive(),source:evidence}).optional(),
 opportunityResearch:z.object({earnings:earningsResearch,financialStrength:financialResearch.optional(),secFilings:filingResearch.optional(),technicalTiming:technicalResearch.optional()}).optional(),
 contractLiabilities:z.object({amount:z.number().finite(),currency:z.string().max(8),asOf:z.string(),source:z.string().max(1000)}).optional(),
 shareCountRatio:number,dailyChange:number,cash:number,debt:number,fcfYield:number,revenueGrowth:number,operatingMarginTrend:number,grossMargin:number,high52w:number,volume:number,averageVolume10d:number,
 analystTarget:number,targetMean:number,targetLow:number,targetHigh:number,analystCount:number,employees:number,insiderBuyValue:number,
 description:z.string().max(20000).optional(),descriptionAr:z.string().max(20000).optional(),nameAr:z.string().max(200).optional(),website:z.string().url().max(500).optional(),sector:z.string().max(200).optional(),sectorAr:z.string().max(200).optional(),industry:z.string().max(200).optional(),industryAr:z.string().max(200).optional(),
 nextEarnings:z.string().max(40).nullable().optional(),lastEarnings:z.string().max(40).nullable().optional(),lastEarningsStatus:z.enum(['إيجابي','سلبي','مختلط','غير معروف']).optional(),
 surprises:z.array(z.object({quarter:z.string().max(40),surprisePct:number,actual:number,estimate:number})).max(30).optional(),
 revenueTrend:z.array(z.object({quarter:z.string().max(40),value:z.number().finite(),periodEnd:z.string().optional()})).max(50).optional(),
 news:z.array(z.object({title:z.string().max(2000),titleAr:z.string().max(2000).optional(),link:z.string().url().refine(u=>/^https?:\/\//.test(u)).optional(),publishedAt:z.string().max(80).optional(),source:z.string().max(200).optional(),sourceAr:z.string().max(200).optional()})).max(100).optional(),
 insiderResearch:z.object({state:z.enum(['complete','partial','unavailable']),windowStart:z.string(),windowEnd:z.string(),availableForm4Count:positiveCount,selectedForm4Count:positiveCount,fetchedForm4Count:positiveCount,failedForm4Count:positiveCount,reviewedForm4Count:positiveCount,invalidForm4Count:positiveCount,unattemptedForm4Count:positiveCount,httpStatusCounts:z.record(positiveCount),submissionWindowComplete:z.boolean(),message:z.string().max(10000)}).optional(),
 insiderPurchases:z.array(z.object({owner:z.string().max(300),date:z.string().max(40),shares:z.number().finite().positive(),price:z.number().finite().nonnegative(),value:z.number().finite().nonnegative(),filed:z.string().max(40).optional(),contentHash:z.string().regex(/^[a-f0-9]{64}$/).optional(),source:z.string().url().optional()})).max(100).optional(),
 backlog:z.object({kind:z.enum(['remaining-performance-obligation','backlog','contract-liability','unclassified']).optional(),expectedRecognitionBy:z.string().optional(),amount:number,currency:z.string().max(8).optional(),asOf:z.string().max(40).optional(),stale:z.boolean().optional(),source:z.string().url().optional()}).nullable().optional(),
}).strict();
export const importSchema=z.array(completeSnapshotSchema).min(1).max(500).refine(rows=>new Set(rows.map(r=>r.symbol)).size===rows.length,'Duplicate symbols are not allowed');
