import {sqliteTable,text,integer,real,index} from 'drizzle-orm/sqlite-core';
export const runs=sqliteTable('strategy_runs',{id:text('id').primaryKey(),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull(),status:text('status').notNull(),source:text('source').notNull(),stage:integer('stage').notNull().default(0),offset:integer('offset').notNull().default(0),processed:integer('processed').notNull().default(0),total:integer('total').notNull().default(0),failed:integer('failed').notNull().default(0),error:text('error'),universe:text('universe'),strategyHash:text('strategy_hash').notNull(),leaseUntil:integer('lease_until').notNull().default(0),retryQueue:text('retry_queue').notNull().default('[]')});
export const snapshots=sqliteTable('fundamental_snapshots',{id:text('id').primaryKey(),runId:text('run_id').notNull().references(()=>runs.id),symbol:text('symbol').notNull(),asOf:text('as_of').notNull(),payload:text('payload').notNull(),evaluation:text('evaluation').notNull()},t=>[index('snapshot_run_idx').on(t.runId)]);
export const favorites=sqliteTable('watchlist',{symbol:text('symbol').primaryKey(),createdAt:text('created_at').notNull()});
export const cache=sqliteTable('raw_cache',{key:text('key').primaryKey(),source:text('source').notNull(),retrievedAt:text('retrieved_at').notNull(),payload:text('payload').notNull()});
export const diagnostics=sqliteTable('diag',{id:text('id').primaryKey(),runId:text('run_id'),stage:text('stage').notNull(),createdAt:text('created_at').notNull(),message:text('message').notNull()});
export const experiments=sqliteTable('experiment_registry',{id:text('id').primaryKey(),hypothesis:text('hypothesis').notNull(),parameters:text('parameters').notNull(),createdAt:text('created_at').notNull(),datasetVersion:text('dataset_version').notNull(),result:text('result'),pValue:real('p_value'),adjustedP:real('adjusted_p'),status:text('status').notNull()});
export const holdouts=sqliteTable('holdout_sets',{firmId:text('firm_id').primaryKey(),membership:text('membership').notNull(),saltHash:text('salt_hash').notNull(),consumedAt:text('consumed_at')});
export const backtests=sqliteTable('backtest_runs',{id:text('id').primaryKey(),createdAt:text('created_at').notNull(),strategyHash:text('strategy_hash').notNull(),datasetVersion:text('dataset_version').notNull(),parameters:text('parameters').notNull(),metrics:text('metrics').notNull()});
